# Generated by Django 3.1.14 on 2022-05-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20220519_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, default='покемон с описанием', verbose_name='Описание'),
        ),
    ]
