# Generated by Django 3.1.14 on 2022-05-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20220520_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemonentity',
            options={'verbose_name': 'Сущность покемона', 'verbose_name_plural': 'Сущность покемонов'},
        ),
    ]
