# Generated by Django 3.1.14 on 2022-05-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_auto_20220524_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemonelementtype',
            options={'verbose_name': 'Стихия', 'verbose_name_plural': 'Стихии'},
        ),
        migrations.AddField(
            model_name='pokemonelementtype',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/element_type/%Y/%m'),
        ),
    ]
